version: "1"
rules:
  - base: master
    upstream: Wurst-Imperium:master
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1
  - base: 1.19.4
    upstream: Wurst-Imperium:23w05a
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1    
