version: "1"
rules:
  - base: master
    upstream: Wurst-Imperium:master
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1
  - base: 1.19.2
    upstream: Wurst-Imperium:1.19.2
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1
  - base: 1.19.4
    upstream: Wurst-Imperium:1.19.4
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1
  - base: 1.16.5
    upstream: Wurst-Imperium:1.16.5
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1
  - base: 1.19.3
    upstream: Wurst-Imperium:1.19.3
    mergeMethod: merge
    assignees:
      - buiawpkgew1
    conflictReviewers:
      - buiawpkgew1