name: 更新 Gradle 依赖关系图

on:
  push:
    branches:
      # Submitting dependency graph reports on non-default branches does nothing
      - "master"
    tags-ignore:
      - "**"
    paths:
      - "gradle**"
      - "*.gradle"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:

    - name: 检出仓库
      uses: actions/checkout@v4

    - name: 设置 Java 21
      uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "microsoft"

    - name: 为 gradlew 授予执行权限
      run: chmod +x gradlew

    - name: 生成并提交依赖关系图
      uses: gradle/actions/dependency-submission@v4
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
        build-scan-terms-of-use-agree: "yes"
