# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle wrapper upgrade

on:
  workflow_dispatch:
      

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3.9.0
      with:
        java-version: 17
        distribution: 'zulu'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle wrapper upgrade
      run: ./gradlew wrapper --gradle-version=7.6 --distribution-type=bin
    - name: Commit change
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin master
        git add gradle/wrapper/gradle-wrapper.jar
        git add gradle/wrapper/gradle-wrapper.properties
        git add gradlew
        git add gradlew.bat
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') Gradle wrapper upgrade"
    - name: Push
      uses:  ad-m/github-push-action@master
      with:
        branch: master
    
