name: Download translations from Transifex

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 结账代码
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
      - name: Install deps
        run: yarn
      - name: 更新翻译
        run: node scripts/transifex pull
        env:
          TRANSIFEX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
      - name: 创建拉动请求
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: i18n-patch
          commit-message: 从Transifex中更新locale文件
          title: 从Transifex中更新locale文件
          body: >-
            Violentmonkey每周自动更新Transifex的译文.

            If you want to help translate into your language, please visit [the transifex platform](https://www.transifex.com/projects/p/violentmonkey-nex/resource/messagesjson/).