name: Automatic build/issue

on:
  push:
    branches: [ 1.18 ]
  pull_request:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 设置JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: 用Gradle构建
      run: ./gradlew build
    - name: 自动释放
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "1.18"
        prerelease: true
        title: "wurst Automatic build versions"
        files: |
          build/libs/Wurst-Client-*-sources.jar
