# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: spotless fix

on:
  workflow_dispatch:
      

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3.13.0
      with:
        java-version: 21
        distribution: 'zulu'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: 使用Spotless修复代码
      id: spotless_Apply
      run: ./gradlew :spotlessApply
    # - name: Gradle wrapper upgrade
    #   run: ./gradlew wrapper --gradle-version=8.0 --distribution-type=bin
    - name: Commit change
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin spotless
        git add src/main/java/net/wurstclient/hacks/TillauraHack.java
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') Gradle wrapper upgrade"
    - name: Push
      uses:  ad-m/github-push-action@master
      with:
        branch: spotless
    
