name: "Close stale issues and pull requests"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: |
            这个问题已经开放了一段时间，最近没有任何活动。如果这个问题对您仍然重要，请在接下来的7天内添加一条评论以保持其开放状态。否则，为了释放时间用于其他任务，这个问题将会被自动关闭。

            问题应该在以下情况下关闭：
            - 它们是其他问题的重复
            - 没有足够的需求
            - 它们不再相关
            - 没有足够的详细信息
          stale-pr-message: |
            这个拉取请求已经开放了一段时间，最近没有任何活动。如果您仍在继续工作或等待审阅，请在接下来的7天内添加评论或提交以保持其开放状态。否则，拉取请求将会自动关闭，以释放时间用于其他任务。

            拉取请求应该在以下情况下关闭：
            - 它们已被另一个拉取请求取代
            - 它们超出了范围或与项目不符
            - 它们因其他更改而变得过时
            - 它们存在无法解决的错误或冲突
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: "status:stale"
          stale-pr-label: "status:stale"
